# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VouchrReactNative' do
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VouchrReactNative

pod 'React', :path => '../node_modules/react-native', :subspecs => [ 'RCTImage', ]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  platform :ios, '9.0'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'VouchrReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'VouchrReactNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VouchrReactNative-tvOS

  target 'VouchrReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
